// Comprehensive filterable columns for History Record
// Generated from history-record-data-table column definitions

import { FilterableColumn } from "@/app/lib/types/filter"

export const historyFilterableColumns: FilterableColumn[] = [
    { id: 'COACHNO', label: 'Coach No', type: 'string' },
    { id: 'SR_NO', label: 'SR No', type: 'string' },
    { id: 'FCOACHNO', label: 'F Coach No', type: 'string' },
    { id: 'OCOACHNO', label: 'O Coach No', type: 'string' },
    { id: 'CODE', label: 'Code', type: 'string' },
    { id: 'TYPE', label: 'Type', type: 'string' },
    { id: 'STATUS', label: 'Status', type: 'string' },
    { id: 'BASEDEPOT', label: 'Base Depot', type: 'string' },
    { id: 'MAKE', label: 'Make', type: 'string' },
    { id: 'YRBLT', label: 'Year Built', type: 'number' },
    { id: 'MFGDT', label: 'MFG Date', type: 'date' },
    { id: 'SHOP', label: 'Shop', type: 'string' },
    { id: 'GEN', label: 'Generation', type: 'string' },
    { id: 'SPEED', label: 'Speed', type: 'string' },
    { id: 'ACNAC', label: 'AC/NAC', type: 'string' },
    { id: 'LHBNLHB', label: 'LHB/NLHB', type: 'string' },
    { id: 'AGE', label: 'Age', type: 'number' },
    { id: 'TWEIGHT', label: 'Weight', type: 'number' },
    { id: 'SEAT', label: 'Seats', type: 'number' },
    { id: 'BERTH', label: 'Berths', type: 'number' },
    { id: 'COST', label: 'Cost', type: 'number' },
    { id: 'FUND', label: 'Fund', type: 'string' },
    { id: 'LSHOPOUTDT', label: 'Last Shop Out', type: 'date' },
    { id: 'SHOPINDT', label: 'Shop In Date', type: 'date' },
    { id: 'YARDINDT', label: 'Yard In Date', type: 'date' },
    { id: 'DT_IOH', label: 'IOH Date', type: 'date' },
    { id: 'DUESCH', label: 'Due Schedule', type: 'string' },
    { id: 'POHBY', label: 'POH By', type: 'string' },
    { id: 'CORRSTATUS', label: 'Corrosion Status', type: 'string' },
    { id: 'REMASTER', label: 'Remaster', type: 'string' },
    { id: 'RAKESING', label: 'Rake Sing', type: 'string' },
    { id: 'ABOEM', label: 'AB OEM', type: 'string' },
    { id: 'CBC', label: 'CBC', type: 'string' },
    { id: 'CBCBY', label: 'CBC By', type: 'string' },
    { id: 'CBCOEM', label: 'CBC OEM', type: 'string' },
    { id: 'COUPLING', label: 'Coupling', type: 'string' },
    { id: 'CORRMHRS', label: 'Corrosion Hours', type: 'number' },
    { id: 'PERIOD', label: 'Period', type: 'number' },
    { id: 'LPOHBY', label: 'Last POH By', type: 'string' },
    { id: 'RETPOHDT', label: 'Return POH Date', type: 'date' },
    { id: 'AGE_RT_DT', label: 'Age Return Date', type: 'number' },
    { id: 'RET_DT_IOH', label: 'Return IOH Date', type: 'date' },
    { id: 'LOC', label: 'Location', type: 'string' },
    { id: 'MECHSUP', label: 'Mech Sup', type: 'string' },
    { id: 'LIFTDT', label: 'Lift Date', type: 'date' },
    { id: 'LOWERDT', label: 'Lower Date', type: 'date' },
    { id: 'RELIFTDT', label: 'Re-Lift Date', type: 'date' },
    { id: 'AIRBKDT', label: 'Air Brake Date', type: 'date' },
    { id: 'PTINDT', label: 'PT In Date', type: 'date' },
    { id: 'HPPTOUTDT', label: 'HP PT Out Date', type: 'date' },
    { id: 'HPPTINDT', label: 'HP PT In Date', type: 'date' },
    { id: 'PTOUTDT', label: 'PT Out Date', type: 'date' },
    { id: 'INSHOP_POS', label: 'In Shop Pos', type: 'string' },
    { id: 'TANKFITOLD', label: 'Tank Fit Old', type: 'number' },
    { id: 'TANKFITNEW', label: 'Tank Fit New', type: 'number' },
    { id: 'RMPUDT', label: 'RMPU Date', type: 'date' },
    { id: 'BATTERYLD', label: 'Battery Load', type: 'string' },
    { id: 'FANLOAD', label: 'Fan Load', type: 'string' },
    { id: 'LIGHTLOAD', label: 'Light Load', type: 'string' },
    { id: 'UTKRISHT', label: 'Utkrisht', type: 'string' },
    { id: 'LAVUPGRADE', label: 'Lav Upgrade', type: 'string' },
    { id: 'VENTURY', label: 'Ventury', type: 'number' },
    { id: 'UPHOLSTRY', label: 'Upholstery', type: 'string' },
    { id: 'DYNO', label: 'Dyno', type: 'string' },
    { id: 'EPOXY', label: 'Epoxy', type: 'string' },
    { id: 'H_CORR', label: 'H Corr', type: 'string' },
    { id: 'H_CORR_DT', label: 'H Corr Date', type: 'date' },
    { id: 'INISSUE', label: 'In Issue', type: 'date' },
    { id: 'DATE_COND', label: 'Date Cond', type: 'date' },
    { id: 'WORKDAYS', label: 'Work Days', type: 'number' },
    { id: 'CALDAYS', label: 'Cal Days', type: 'number' },
    { id: 'DCWIFIT', label: 'DC WI Fit', type: 'date' },
    { id: 'ELECRACFIT', label: 'Elec Rac Fit', type: 'date' },
    { id: 'NTXRFIT', label: 'NTXR Fit', type: 'date' },
    { id: 'ISSUEDT', label: 'Issue Date', type: 'date' },
    { id: 'COND_POS', label: 'Cond Pos', type: 'number' },
    { id: 'COND_BY', label: 'Cond By', type: 'string' },
    { id: 'SERVICE', label: 'Service', type: 'number' },
    { id: 'RSP', label: 'RSP', type: 'string' },
    { id: 'C_R', label: 'C R', type: 'date' },
    { id: 'OTHER_3', label: 'Other 3', type: 'string' },
    { id: 'MEMO', label: 'Memo', type: 'string' },
    { id: 'CTYPE', label: 'C Type', type: 'string' },
    { id: 'ROAMSDT', label: 'Roams Date', type: 'date' },
    { id: 'ACME', label: 'ACME', type: 'date' },
    { id: 'INSP_DT', label: 'Insp Date', type: 'date' },
    { id: 'ROAMSOUTDT', label: 'Roams Out Date', type: 'date' },
    { id: 'REMARK', label: 'Remark', type: 'string' },
]
