// Comprehensive filterable columns for Master Record
// Generated from master-record-data-table column definitions

import { FilterableColumn } from "@/app/lib/types/filter"

export const masterFilterableColumns: FilterableColumn[] = [
    { id: 'coachno', label: 'Coach No', type: 'string' },
    { id: 'fcoachno', label: 'F Coach No', type: 'string' },
    { id: 'ocoachno', label: 'O Coach No', type: 'string' },
    { id: 'code', label: 'Code', type: 'string' },
    { id: 'type', label: 'Type', type: 'string' },
    { id: 'status', label: 'Status', type: 'string' },
    { id: 'basedepot', label: 'Base Depot', type: 'string' },
    { id: 'make', label: 'Make', type: 'string' },
    { id: 'yrblt', label: 'Year Built', type: 'number' },
    { id: 'mfgdt', label: 'MFG Date', type: 'date' },
    { id: 'shop', label: 'Shop', type: 'string' },
    { id: 'gen', label: 'Generation', type: 'string' },
    { id: 'speed', label: 'Speed', type: 'string' },
    { id: 'acnac', label: 'AC/NAC', type: 'string' },
    { id: 'lhbnlhb', label: 'LHB/NLHB', type: 'string' },
    { id: 'age', label: 'Age', type: 'number' },
    { id: 'tweight', label: 'Weight', type: 'number' },
    { id: 'seat', label: 'Seats', type: 'number' },
    { id: 'berth', label: 'Berths', type: 'number' },
    { id: 'cost', label: 'Cost', type: 'number' },
    { id: 'fund', label: 'Fund', type: 'string' },
    { id: 'lshopoutdt', label: 'Last Shop Out', type: 'date' },
    { id: 'shopindt', label: 'Shop In Date', type: 'date' },
    { id: 'yardindt', label: 'Yard In Date', type: 'date' },
    { id: 'dt_ioh', label: 'IOH Date', type: 'date' },
    { id: 'duesch', label: 'Due Schedule', type: 'string' },
    { id: 'pohby', label: 'POH By', type: 'string' },
    { id: 'corrstatus', label: 'Corrosion Status', type: 'string' },
    { id: 're_placed', label: 'Re Placed', type: 'string' },
    { id: 'dt_placed', label: 'Date Placed', type: 'date' },
    { id: 'comdt', label: 'Com Date', type: 'date' },
    { id: 'remaster', label: 'Remaster', type: 'string' },
    { id: 'books', label: 'Books', type: 'string' },
    { id: 'rakesing', label: 'Rake Sing', type: 'string' },
    { id: 'overagedt', label: 'Overage Date', type: 'date' },
    { id: 'aboem', label: 'AB OEM', type: 'string' },
    { id: 'bktype', label: 'Brake Type', type: 'string' },
    { id: 'cbc', label: 'CBC', type: 'string' },
    { id: 'cbcby', label: 'CBC By', type: 'string' },
    { id: 'cbcoem', label: 'CBC OEM', type: 'string' },
    { id: 'coupling', label: 'Coupling', type: 'string' },
    { id: 'corrmhrs', label: 'Corrosion Hours', type: 'number' },
    { id: 'period', label: 'Period', type: 'number' },
    { id: 'lpohby', label: 'Last POH By', type: 'string' },
    { id: 'retpohdt', label: 'Return POH Date', type: 'date' },
    { id: 'age_rt_dt', label: 'Age Return Date', type: 'number' },
    { id: 'ret_dt_ioh', label: 'Return IOH Date', type: 'date' },
    { id: 'mlrdt', label: 'MLR Date', type: 'date' },
    { id: 'mlrby', label: 'MLR By', type: 'string' },
    { id: 'date_rf', label: 'Date RF', type: 'date' },
    { id: 'date_conv', label: 'Date Conv', type: 'date' },
    { id: 'lschedule', label: 'Last Schedule', type: 'string' },
    { id: 'ns_ss2_3', label: 'NS SS2/3', type: 'string' },
    { id: 'allot', label: 'Allotment', type: 'string' },
    { id: 'rfid_det', label: 'RFID Detail', type: 'string' },
    { id: 'rmpu', label: 'RMPU', type: 'string' },
    { id: 'liftdt', label: 'Lift Date', type: 'date' },
    { id: 'lowerdt', label: 'Lower Date', type: 'date' },
    { id: 'reliftdt', label: 'Re-Lift Date', type: 'date' },
    { id: 'airbkdt', label: 'Air Brake Date', type: 'date' },
    { id: 'ptindt', label: 'PT In Date', type: 'date' },
    { id: 'rfid_dv', label: 'RFID DV', type: 'string' },
    { id: 'rfid_nondv', label: 'RFID Non-DV', type: 'string' },
    { id: 'ptoutdt', label: 'PT Out Date', type: 'date' },
    { id: 'cmm_mdepot', label: 'CMM MDepot', type: 'string' },
    { id: 'tankfitold', label: 'Tank Fit Old', type: 'number' },
    { id: 'tankfitnew', label: 'Tank Fit New', type: 'number' },
    { id: 'tankmfg', label: 'Tank MFG', type: 'string' },
    { id: 'batteryld', label: 'Battery Load', type: 'string' },
    { id: 'fanload', label: 'Fan Load', type: 'string' },
    { id: 'lightload', label: 'Light Load', type: 'string' },
    { id: 'utkrisht', label: 'Utkrisht', type: 'string' },
    { id: 'lavupgrade', label: 'Lav Upgrade', type: 'string' },
    { id: 'ventury', label: 'Ventury', type: 'number' },
    { id: "upholstry", label: "Upholstery", type: "string" },
    { id: "dyno", label: "Dyno", type: "string" },
    { id: "cmm_depot", label: "CMM Depot", type: "string" },
    { id: "h_corr", label: "H Corr", type: "string" },
    { id: "h_corr_dt", label: "H Corr Date", type: "date" },
    { id: "inissue", label: "In Issue", type: "date" },
    { id: "remark", label: "Remark", type: "string" },
    { id: "workdays", label: "Work Days", type: "number" },
    { id: "caldays", label: "Cal Days", type: "number" },
    { id: "dcwifit", label: "DC WI Fit", type: "date" },
    { id: "elecracfit", label: "Elec Rac Fit", type: "date" },
    { id: "ntxrfit", label: "NTXR Fit", type: "date" },
    { id: "issuedt", label: "Issue Date", type: "string" },
    { id: "innhs1", label: "In NHS 1", type: "string" },
    { id: "innhs1dt", label: "In NHS 1 Date", type: "date" },
    { id: "innhs2", label: "In NHS 2", type: "string" },
    { id: "innhs2dt", label: "In NHS 2 Date", type: "date" },
    { id: "cond_pos", label: "Cond Pos", type: "number" },
    { id: "date_cond", label: "Date Cond", type: "string" },
    { id: "insp_dt", label: "Insp Date", type: "date" },
    { id: "ioh_by", label: "IOH By", type: "string" },
    { id: "tnk_c_by", label: "Tank C By", type: "string" },
    { id: "other_3", label: "Other 3", type: "string" },
    { id: "fiba", label: "FIBA", type: "string" },
    { id: "asv", label: "ASV", type: "string" },
    { id: "wsp", label: "WSP", type: "string" },
    { id: "l_3yr_done", label: "L 3Yr Done", type: "date" },
    { id: "l_6yr_done", label: "L 6Yr Done", type: "date" },
    { id: "l_9yr_done", label: "L 9Yr Done", type: "date" },
    { id: "l_3yr_due", label: "L 3Yr Due", type: "date" },
    { id: "l_6yr_due", label: "L 6Yr Due", type: "date" },
    { id: "c_r", label: "C R", type: "string" },
    { id: "abk", label: "ABK", type: 'string' },
    { id: "rl", label: "RL", type: 'string' },
    { id: "pt", label: "PT", type: 'string' },
    { id: "lif", label: "LIF", type: 'string' },
    { id: "suspension", label: "Suspension", type: 'string' },
    { id: "elra", label: "ELRA", type: 'string' },
    { id: "l_9yr_due", label: "L 9Yr Due", type: "date" },
    { id: "uphlddt", label: "Uphld Date", type: "date" },
    { id: "acme", label: "ACME", type: "date" },
    { id: "pfs", label: "PFS", type: "string" },
    { id: "uphundt", label: "Uphun Date", type: "date" },
    { id: "btlddt", label: "Btld Date", type: "date" },
    { id: "btundt", label: "Btun Date", type: "date" },
    { id: "bt", label: "BT", type: "string" },
    { id: "uph", label: "UPH", type: "string" },
    { id: "rly", label: "RLY", type: "string" },
    { id: "ctype", label: "C Type", type: "string" },
    { id: "roamsdt", label: "Roams Date", type: "date" },
    { id: "bvt", label: "BVT", type: "string" },
]
